=== exponea/bloomreach-magento2-integration/etc/bloomreach_entity_mapping.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
    <xs:element name="config" type="configType">
    </xs:element>
    <xs:complexType name="entityType">
        <xs:sequence>
            <xs:element type="bloomreachCodeType" name="bloomreach_code" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="entity" use="required"/>
    </xs:complexType>
    <xs:complexType name="bloomreachCodeType">
        <xs:sequence>
            <xs:element type="fieldType" maxOccurs="unbounded" name="field" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="code" use="required"/>
        <xs:attribute type="xs:string" name="type" use="optional"/>
        <xs:attribute name="disabled" type="xs:boolean" use="optional" />
    </xs:complexType>
    <xs:complexType name="configType">
        <xs:sequence>
            <xs:element type="entityType" name="entity_type" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="fieldType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="code" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== exponea/bloomreach-magento2-integration/etc/bloomreach_entity_mapping.xml
<?xml version="1.0"?>
<!--
/**
 * @author Bloomreach
 * @copyright Copyright (c) Bloomreach (https://www.bloomreach.com/)
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Bloomreach_EngagementConnector:etc/bloomreach_entity_mapping.xsd">
    <entity_type entity="catalog_product">
        <bloomreach_code code="item_id" type="number">
            <field code="entity_id"/>
        </bloomreach_code>
        <bloomreach_code code="sku" type="string">
            <field code="sku"/>
        </bloomreach_code>
        <bloomreach_code code="active" type="boolean">
            <field code="status"/>
        </bloomreach_code>
        <bloomreach_code code="image" type="string">
            <field code="image"/>
        </bloomreach_code>
        <bloomreach_code code="title" type="string">
            <field code="name"/>
        </bloomreach_code>
        <bloomreach_code code="description" type="long text">
            <field code="short_description"/>
        </bloomreach_code>
        <bloomreach_code code="description_long" type="long text">
            <field code="description"/>
        </bloomreach_code>
        <bloomreach_code code="url" type="string">
            <field code="url"/>
        </bloomreach_code>
        <bloomreach_code code="supplier" type="string">
            <field code="manufacturer"/>
        </bloomreach_code>
        <bloomreach_code code="gender" type="string">
            <field code="gender"/>
        </bloomreach_code>
        <bloomreach_code code="rating" type="number">
            <field code="rating"/>
        </bloomreach_code>
        <bloomreach_code code="ratings_count" type="number">
            <field code="ratings_count"/>
        </bloomreach_code>
        <bloomreach_code code="category_level_1" type="string">
            <field code="category_level_1"/>
        </bloomreach_code>
        <bloomreach_code code="category_1_url" type="string">
            <field code="category_1_url"/>
        </bloomreach_code>
        <bloomreach_code code="category_level_2" type="string">
            <field code="category_level_2"/>
        </bloomreach_code>
        <bloomreach_code code="category_2_url" type="string">
            <field code="category_2_url"/>
        </bloomreach_code>
        <bloomreach_code code="category_level_3" type="string">
            <field code="category_level_3"/>
        </bloomreach_code>
        <bloomreach_code code="category_3_url" type="string">
            <field code="category_3_url"/>
        </bloomreach_code>
        <bloomreach_code code="categories_path" type="string">
            <field code="categories_path"/>
        </bloomreach_code>
        <bloomreach_code code="categories_ids" type="list">
            <field code="categories_ids"/>
        </bloomreach_code>
        <bloomreach_code code="color" type="string">
            <field code="color"/>
        </bloomreach_code>
        <bloomreach_code code="size" type="string">
            <field code="size"/>
        </bloomreach_code>
        <bloomreach_code code="price" type="number">
            <field code="final_price"/>
        </bloomreach_code>
        <bloomreach_code code="original_price" type="number">
            <field code="price"/>
        </bloomreach_code>
        <bloomreach_code code="discount_percentage" type="number">
            <field code="discount_percentage"/>
        </bloomreach_code>
        <bloomreach_code code="discount_value" type="number">
            <field code="discount_value"/>
        </bloomreach_code>
        <bloomreach_code code="on_sale" type="boolean">
            <field code="sale"/>
        </bloomreach_code>
        <bloomreach_code code="date_added" type="number">
            <field code="created_at"/>
        </bloomreach_code>
        <bloomreach_code code="stock_level" type="number">
            <field code="stock_level"/>
        </bloomreach_code>
        <bloomreach_code code="image_fullsize" type="string">
            <field code="image"/>
        </bloomreach_code>
    </entity_type>
    <entity_type entity="catalog_product_variants">
        <bloomreach_code code="item_id" type="number">
            <field code="entity_id"/>
        </bloomreach_code>
        <bloomreach_code code="sku" type="string">
            <field code="sku"/>
        </bloomreach_code>
        <bloomreach_code code="product_id" type="number">
            <field code="product_id"/>
        </bloomreach_code>
        <bloomreach_code code="active" type="boolean">
            <field code="status"/>
        </bloomreach_code>
        <bloomreach_code code="product_active" type="boolean">
            <field code="product_active"/>
        </bloomreach_code>
        <bloomreach_code code="stock_level" type="number">
            <field code="stock_level"/>
        </bloomreach_code>
        <bloomreach_code code="product_sku" type="string">
            <field code="product_sku"/>
        </bloomreach_code>
        <bloomreach_code code="title" type="string">
            <field code="name"/>
        </bloomreach_code>
        <bloomreach_code code="description" type="long text">
            <field code="short_description"/>
        </bloomreach_code>
        <bloomreach_code code="description_long" type="long text">
            <field code="description"/>
        </bloomreach_code>
        <bloomreach_code code="url" type="string">
            <field code="url"/>
        </bloomreach_code>
        <bloomreach_code code="supplier" type="string">
            <field code="manufacturer"/>
        </bloomreach_code>
        <bloomreach_code code="rating" type="number">
            <field code="rating"/>
        </bloomreach_code>
        <bloomreach_code code="ratings_count" type="number">
            <field code="ratings_count"/>
        </bloomreach_code>
        <bloomreach_code code="category_level_1" type="string">
            <field code="category_level_1"/>
        </bloomreach_code>
        <bloomreach_code code="category_1_url" type="string">
            <field code="category_1_url"/>
        </bloomreach_code>
        <bloomreach_code code="category_level_2" type="string">
            <field code="category_level_2"/>
        </bloomreach_code>
        <bloomreach_code code="category_2_url" type="string">
            <field code="category_2_url"/>
        </bloomreach_code>
        <bloomreach_code code="category_level_3" type="string">
            <field code="category_level_3"/>
        </bloomreach_code>
        <bloomreach_code code="category_3_url" type="string">
            <field code="category_3_url"/>
        </bloomreach_code>
        <bloomreach_code code="categories_path" type="string">
            <field code="categories_path"/>
        </bloomreach_code>
        <bloomreach_code code="categories_ids" type="list">
            <field code="categories_ids"/>
        </bloomreach_code>
        <bloomreach_code code="size" type="string">
            <field code="size"/>
        </bloomreach_code>
        <bloomreach_code code="color" type="string">
            <field code="color"/>
        </bloomreach_code>
        <bloomreach_code code="price" type="number">
            <field code="final_price"/>
        </bloomreach_code>
        <bloomreach_code code="original_price" type="number">
            <field code="price"/>
        </bloomreach_code>
        <bloomreach_code code="discount_percentage" type="number">
            <field code="discount_percentage"/>
        </bloomreach_code>
        <bloomreach_code code="discount_value" type="number">
            <field code="discount_value"/>
        </bloomreach_code>
        <bloomreach_code code="on_sale" type="boolean">
            <field code="sale"/>
        </bloomreach_code>
        <bloomreach_code code="date_added" type="number">
            <field code="created_at"/>
        </bloomreach_code>
        <bloomreach_code code="image" type="string">
            <field code="image"/>
        </bloomreach_code>
        <bloomreach_code code="gender" type="string">
            <field code="gender"/>
        </bloomreach_code>
        <bloomreach_code code="image_fullsize" type="string">
            <field code="image"/>
        </bloomreach_code>
    </entity_type>
    <entity_type entity="customer">
        <bloomreach_code code="email_id" type="string">
            <field code="email"/>
        </bloomreach_code>
        <bloomreach_code code="customer_id" type="number">
            <field code="entity_id"/>
        </bloomreach_code>
        <bloomreach_code code="email" type="string">
            <field code="email"/>
        </bloomreach_code>
        <bloomreach_code code="first_name" type="string">
            <field code="firstname"/>
        </bloomreach_code>
        <bloomreach_code code="last_name" type="string">
            <field code="lastname"/>
        </bloomreach_code>
        <bloomreach_code code="gender" type="string">
            <field code="gender"/>
        </bloomreach_code>
        <bloomreach_code code="company" type="string">
            <field code="company"/>
        </bloomreach_code>
        <bloomreach_code code="phone" type="string">
            <field code="telephone"/>
        </bloomreach_code>
        <bloomreach_code code="birth_date" type="number">
            <field code="dob"/>
        </bloomreach_code>
        <bloomreach_code code="country" type="string">
            <field code="country"/>
        </bloomreach_code>
        <bloomreach_code code="state" type="string">
            <field code="region"/>
        </bloomreach_code>
    </entity_type>
    <entity_type entity="purchase">
        <bloomreach_code code="email_id" type="string">
            <field code="customer_email"/>
        </bloomreach_code>
        <bloomreach_code code="customer_id" type="number">
            <field code="customer_id"/>
        </bloomreach_code>
